"""Plant Columns added

Revision ID: f7868c99f9ca
Revises: 1a3f458d859e
Create Date: 2024-01-17 11:04:20.562048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7868c99f9ca'
down_revision = '1a3f458d859e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(length=500), nullable=True))
    op.add_column('plants', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('plants', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
