"""Added gender in student table

Revision ID: 0650e2a55156
Revises: 015cc467888e
Create Date: 2024-01-10 10:44:59.841578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0650e2a55156'
down_revision: Union[str, None] = '015cc467888e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('gender', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'gender')
    # ### end Alembic commands ###
